require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BilisController do

  # This should return the minimal set of attributes required to create a valid
  # Bili. As you add validations to Bili, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "page" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BilisController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bilis as @bilis" do
      bili = Bili.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bilis).should eq([bili])
    end
  end

  describe "GET show" do
    it "assigns the requested bili as @bili" do
      bili = Bili.create! valid_attributes
      get :show, {:id => bili.to_param}, valid_session
      assigns(:bili).should eq(bili)
    end
  end

  describe "GET new" do
    it "assigns a new bili as @bili" do
      get :new, {}, valid_session
      assigns(:bili).should be_a_new(Bili)
    end
  end

  describe "GET edit" do
    it "assigns the requested bili as @bili" do
      bili = Bili.create! valid_attributes
      get :edit, {:id => bili.to_param}, valid_session
      assigns(:bili).should eq(bili)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bili" do
        expect {
          post :create, {:bili => valid_attributes}, valid_session
        }.to change(Bili, :count).by(1)
      end

      it "assigns a newly created bili as @bili" do
        post :create, {:bili => valid_attributes}, valid_session
        assigns(:bili).should be_a(Bili)
        assigns(:bili).should be_persisted
      end

      it "redirects to the created bili" do
        post :create, {:bili => valid_attributes}, valid_session
        response.should redirect_to(Bili.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bili as @bili" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bili.any_instance.stub(:save).and_return(false)
        post :create, {:bili => { "page" => "invalid value" }}, valid_session
        assigns(:bili).should be_a_new(Bili)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bili.any_instance.stub(:save).and_return(false)
        post :create, {:bili => { "page" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bili" do
        bili = Bili.create! valid_attributes
        # Assuming there are no other bilis in the database, this
        # specifies that the Bili created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bili.any_instance.should_receive(:update_attributes).with({ "page" => "" })
        put :update, {:id => bili.to_param, :bili => { "page" => "" }}, valid_session
      end

      it "assigns the requested bili as @bili" do
        bili = Bili.create! valid_attributes
        put :update, {:id => bili.to_param, :bili => valid_attributes}, valid_session
        assigns(:bili).should eq(bili)
      end

      it "redirects to the bili" do
        bili = Bili.create! valid_attributes
        put :update, {:id => bili.to_param, :bili => valid_attributes}, valid_session
        response.should redirect_to(bili)
      end
    end

    describe "with invalid params" do
      it "assigns the bili as @bili" do
        bili = Bili.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bili.any_instance.stub(:save).and_return(false)
        put :update, {:id => bili.to_param, :bili => { "page" => "invalid value" }}, valid_session
        assigns(:bili).should eq(bili)
      end

      it "re-renders the 'edit' template" do
        bili = Bili.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bili.any_instance.stub(:save).and_return(false)
        put :update, {:id => bili.to_param, :bili => { "page" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bili" do
      bili = Bili.create! valid_attributes
      expect {
        delete :destroy, {:id => bili.to_param}, valid_session
      }.to change(Bili, :count).by(-1)
    end

    it "redirects to the bilis list" do
      bili = Bili.create! valid_attributes
      delete :destroy, {:id => bili.to_param}, valid_session
      response.should redirect_to(bilis_url)
    end
  end

end
